<script lang="ts">
	import Fuse from 'fuse.js';
	import VirtualList from '@sveltejs/svelte-virtual-list';
	import { faGithub, faDiscord } from '@fortawesome/free-brands-svg-icons'
	import Fa from 'svelte-fa'
    import Modal, { bind } from 'svelte-simple-modal';
	import { slide } from 'svelte/transition';
	import { onMount } from 'svelte';
	import { modalStore } from '../stores';

	import { all } from '../model/EntryData.svelte';

	import Entry from '../components/Entry.svelte';
	import EntryFull from '../components/EntryFull.svelte';
	import type EntryData from '../model/EntryData.svelte';

    let searchTerm = "";
	const fuse = new Fuse(all, {
    	keys: ['name', 'description'],
		threshold: 0.25,
		includeMatches: true,
		useExtendedSearch: true
    });
	
	type SearchResult = {
		item: EntryData,
		matches?: ReadonlyArray<Fuse.FuseResultMatch>
	};

	// @ts-expect-error
	const allAsSR: SearchResult[] = all.map(v => {return {
		item: v,
		matches: []
	}});
	let searchResults: SearchResult[] = allAsSR;
	$: searchResults = searchTerm.length > 0 ? fuse.search(searchTerm) : allAsSR;

	let showNotice = true;

	onMount(() => {
		if (window.location.hash.length > 0) {
			const entry = all.find(e => e.cleanName === window.location.hash.slice(1));
			if (entry) {
				// @ts-expect-error cba to type this
				modalStore.set(bind(EntryFull, { entry }));
				console.log(entry);
			}
		}
	});
</script>

<svelte:head>
	<title>Signatures for {searchResults.length} functions {searchResults.length === 0 ? "😭" : "🤗"}</title>
</svelte:head>

<div class="flex m-8">
	<div class="flex-1">
		<h1 class="text-4xl">Signatures for {searchResults.length} functions {searchResults.length === 0 ? "😭" : "🤗"}</h1>
	</div>
	<div class="flex justify-end items-center space-x-5">
		<a href="https://horion.download/discord" aria-label="discord"><Fa icon={faDiscord} size="2x"/></a>
		<a href="https://github.com/HorionContinued/sigs" aria-label="github"><Fa icon={faGithub} size="2x"/></a>
	</div>
</div>

<main class="m-5">
	{#if showNotice}
		<div class="w-full h-50 bg-red-400 bg-opacity-40 rounded-xl p-5 flex mb-5" out:slide>
			<div class="flex-1">
				<h1 class="text-xl"><strong>Attention</strong></h1>
				<p>This is a work in progress. If you want to help with documenting these signatures/offsets, feel free to open a pull request on <a href="https://github.com/HorionContinued/sigs/"><u>GitHub</u></a>.</p>
				<p><strong>Note:</strong> The signatures and offsets on this page are autogenerated. They are only correct about <b>80%</b> of the time.</p>	
			</div>
			<div class="flex justify-end items-center text-center">
				<strong class="text-3xl w-10 h-10 cursor-pointer hover:scale-105 transition-all" on:click={() => showNotice = false } on:keypress={() => showNotice = false }>&times;</strong>
			</div>
		</div>
	{/if}
	<div class="mb-5 relative">
		<input bind:value={searchTerm} placeholder="search for name, description or signature..." class="w-full placeholder-text-color bg-white bg-opacity-5 rounded-xl p-2 px-3">
		<span class="absolute right-2 bottom-2 pointer-events-none">
			<svg fill="none" stroke="var(--text-color)" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
		</span>
	</div>
	<div style="height: calc(100vh - {showNotice ? 330 : 195 }px);">
		{#if searchResults.length === 0}
			<div class="text-center">No results</div>
		{:else}
			<VirtualList items={searchResults} let:item>
				<Entry entry={item.item} matches={item.matches}/>
			</VirtualList>
		{/if}
	</div>
</main>

<Modal
	show={$modalStore}
	unstyled={true}
	classBg="fixed top-0 left-0 w-screen h-screen flex flex-col justify-center bg-black/[0.4] backdrop-filter backdrop-blur"
	classWindowWrap="m-10"
	classWindow="max-w-2xl mx-auto rounded-xl shadow-md bg-background-color"
	classContent="p-4"
	closeButton={false}
/>