<script lang="ts">
	import Fuse from 'fuse.js';
	import VirtualList from '@sveltejs/svelte-virtual-list';
	import Fa from 'svelte-fa/src/fa.svelte'
	import { faGithub, faDiscord } from '@fortawesome/free-brands-svg-icons'
	import { writable } from 'svelte/store';
	import { slide } from 'svelte/transition';

	import Function from '../components/Entry.svelte';
	import { all } from '../model/EntryData.svelte';

    const searchTermStore = writable('');
	const fuse = new Fuse(all, {
    	keys: ['name', 'description', 'signature'],
		threshold: 0.25,
		useExtendedSearch: true
    });

	let showNotice = true;
</script>

<svelte:head>
	<title>Signatures for {all.length} functions 🤗</title>
</svelte:head>

<div class="flex m-8">
	<div class="flex-1">
		<h1 class="text-4xl">Signatures for {all.length} functions 🤗</h1>
	</div>
	<div class="flex justify-end items-center">
		<a href="https://horion.download/discord" class=""><Fa icon={faDiscord} size="2x"/></a>
		<div class="w-5"/>
		<a href="https://github.com/HorionContinued/sigs" class=""><Fa icon={faGithub} size="2x"/></a>
	</div>
</div>

<main class="m-5">
	{#if showNotice}
		<div class="w-full h-50 bg-red-400 bg-opacity-40 rounded-xl p-5 flex mb-5" out:slide>
			<div class="flex-1">
				<h1 class="text-xl"><strong>Attention</strong></h1>
				<p>This is a work in progress. If you want to help with documenting these signatures/offsets, feel free to open a pull request on <a href="https://github.com/HorionContinued/sigs/"><u>GitHub</u></a>.</p>
				<p><strong>Note:</strong> The signatures and offsets on this page are autogenerated. They are only correct about <b>80%</b> of the time.</p>	
			</div>
			<div class="flex justify-end items-center text-center">
				<strong class="text-3xl w-10 h-10 cursor-pointer hover:scale-105 transition-all" on:click={() => showNotice = false } on:keypress={() => showNotice = false }>&times;</strong>
			</div>
		</div>
	{/if}
	<div class="mb-5 relative">
		<input bind:value={$searchTermStore} placeholder="search for name, description or signature..." class="w-full placeholder-[var(--text-color)] bg-white bg-opacity-5 rounded-xl p-2 px-3">
		<span class="absolute right-2 bottom-2 pointer-events-none">
			<svg fill="none" stroke="var(--text-color)" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
	  	</span>
	</div>
	<div style="height: calc(100vh - {showNotice ? 330 : 195 }px);">
		{#if $searchTermStore.length > 0}
			{#await fuse.search($searchTermStore)}
				<p>Loading...</p>
			{:then searchResults}
				{#if searchResults.length === 0}
					<div class="text-center">No results</div>
				{:else}
					<VirtualList items={searchResults.map(v => v.item)} let:item>
						<Function entry={item} />
					</VirtualList>
				{/if}
			{/await}
		{:else}
			<VirtualList items={all} let:item>
				<Function entry={item} />
			</VirtualList>
		{/if}
	</div>
</main>