<script lang="ts">
	import Fuse from 'fuse.js';
	import VirtualList from '@sveltejs/svelte-virtual-list';
	import { faGithub, faDiscord } from '@fortawesome/free-brands-svg-icons'
	import Fa from 'svelte-fa'
    import Modal, { bind } from 'svelte-simple-modal';
	import { fly, slide } from 'svelte/transition';
	import { onMount } from 'svelte';
	import { modalStore } from '../stores';

	import Entry from '../components/Entry.svelte';
	import EntryFull from '../components/EntryFull.svelte';
	import type EntryData from '../model/EntryData.svelte'; 

	let all: EntryData[];

	let searchTerm = '';
	let fuse: Fuse<EntryData>;
	$: if(all) fuse = new Fuse(all, {
			keys: ['name', 'description'],
			threshold: 0.25,
			includeMatches: true,
			useExtendedSearch: true
	});
	

	let searchResults: {item: EntryData, matches?: ReadonlyArray<Fuse.FuseResultMatch>}[];
	$: if(fuse) searchResults = (searchTerm.length > 0) ? fuse.search(searchTerm) : all.map(v => ({item: v, matches: []}));
	
	let showNotice = true;

	onMount(async () => {
		let entrydata = await import("../model/EntryData.svelte");
		// @ts-expect-error stupid typescript
		all = await entrydata.get();

		if (window.location.hash.length > 0) {
			const entry = all.find(e => e.cleanName === window.location.hash.slice(1));
			if (entry) {
				// @ts-expect-error cba to type this
				modalStore.set(bind(EntryFull, { entry }));
				console.log(entry);
			}
		}
	});
</script>

<svelte:head>
	{#if searchResults}
		<title>Signatures for {searchResults.length} functions {searchResults.length === 0 ? "😭" : "🤗"}</title>
	{:else}
		<title>Loading...</title>
	{/if}
</svelte:head>

{#if !searchResults} 
<div class="grid place-content-center h-screen" out:slide>
	<svg class="w-8 h-8 fill-secondary-color animate-spin" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
		<path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
		<path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
	</svg>
</div>
{:else}
<div class="flex m-8">
	<div class="flex-1">
		<h1 class="text-4xl">Signatures for {searchResults.length} functions {searchResults.length === 0 ? "😭" : "🤗"}</h1>
	</div>
	<div class="flex justify-end items-center space-x-5">
		<a href="https://horion.download/discord" aria-label="discord"><Fa icon={faDiscord} size="2x"/></a>
		<a href="https://github.com/HorionContinued/sigs" aria-label="github"><Fa icon={faGithub} size="2x"/></a>
	</div>
</div>

<main class="m-5">
	{#if showNotice}
		<div class="w-full h-50 bg-red-400 bg-opacity-40 rounded-xl p-5 flex mb-5" out:slide>
			<div class="flex-1">
				<h1 class="text-xl"><strong>Attention</strong></h1>
				<p>This is a work in progress. If you want to help with documenting these signatures/offsets, feel free to open a pull request on <a href="https://github.com/HorionContinued/sigs/"><u>GitHub</u></a>.</p>
				<p><strong>Note:</strong> The signatures and offsets on this page are autogenerated. They are only correct about <b>80%</b> of the time.</p>	
			</div>
			<div class="flex justify-end items-center text-center">
				<strong class="text-3xl w-10 h-10 cursor-pointer hover:scale-105 transition-all" on:click={() => showNotice = false } on:keypress={() => showNotice = false }>&times;</strong>
			</div>
		</div>
	{/if}
	<div class="mb-5 relative">
		<input bind:value={searchTerm} placeholder="search for name, description or signature..." class="w-full placeholder-text-color bg-white bg-opacity-5 rounded-xl p-2 px-3">
		<span class="absolute right-2 bottom-2 pointer-events-none">
			<svg fill="none" stroke="var(--text-color)" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
		</span>
	</div>
	<div style="height: calc(100vh - {showNotice ? 330 : 195 }px);">
		{#if searchResults.length === 0}
			<div class="text-center">No results</div>
		{:else}
			<VirtualList items={searchResults} let:item>
				<Entry entry={item.item} matches={item.matches} />
			</VirtualList>
		{/if}
	</div>
</main>

<Modal
	show={$modalStore}
	unstyled={true}
	classBg="fixed top-0 left-0 w-screen h-screen flex flex-col justify-center bg-black/[0.4] backdrop-filter backdrop-blur"
	classWindowWrap="m-10"
	classWindow="max-w-2xl mx-auto rounded-xl shadow-md bg-background-color"
	classContent="p-4"
	closeButton={false}
/>
{/if}